import * as Icons from '@/shared/icons'

type CurrencyData = {
  currency: string
  icon: React.ComponentType<{ className?: string }>
}

export const FLAG_TO_CURRENCY: Record<string, CurrencyData> = {
  US: { currency: 'US Dollar', icon: Icons.FlagUsIcon },
  GB: { currency: 'British Pound', icon: Icons.FlagGbIcon },
  EU: { currency: 'Euro', icon: Icons.FlagEuIcon },
  JP: { currency: 'Japanese Yen', icon: Icons.FlagJpIcon },
  CN: { currency: 'Chinese Yuan', icon: Icons.FlagCnIcon },
  IN: { currency: 'Indian Rupee', icon: Icons.FlagInIcon },
  AU: { currency: 'Australian Dollar', icon: Icons.FlagAuIcon },
  CH: { currency: 'Swiss Franc', icon: Icons.FlagChIcon },
  NZ: { currency: 'New Zealand Dollar', icon: Icons.FlagNzIcon },
  SG: { currency: 'Singapore Dollar', icon: Icons.FlagSgIcon },
  HK: { currency: 'Hong Kong Dollar', icon: Icons.FlagHkIcon },
  KR: { currency: 'South Korean Won', icon: Icons.FlagKrIcon },
  BR: { currency: 'Brazilian Real', icon: Icons.FlagBrIcon },
  MX: { currency: 'Mexican Peso', icon: Icons.FlagMxIcon },
  RU: { currency: 'Russian Ruble', icon: Icons.FlagRuIcon },
  ZA: { currency: 'South African Rand', icon: Icons.FlagZaIcon },
  TR: { currency: 'Turkish Lira', icon: Icons.FlagTrIcon },
  ID: { currency: 'Indonesian Rupiah', icon: Icons.FlagIdIcon },
  TH: { currency: 'Thai Baht', icon: Icons.FlagThIcon },
  PH: { currency: 'Philippine Peso', icon: Icons.FlagPhIcon },
  MY: { currency: 'Malaysian Ringgit', icon: Icons.FlagMyIcon },
  VN: { currency: 'Vietnamese Dong', icon: Icons.FlagVnIcon },
  AR: { currency: 'Argentine Peso', icon: Icons.FlagArIcon },
  CL: { currency: 'Chilean Peso', icon: Icons.FlagClIcon },
  CO: { currency: 'Colombian Peso', icon: Icons.FlagCoIcon },
  PE: { currency: 'Peruvian Sol', icon: Icons.FlagPeIcon },
  PL: { currency: 'Polish Zloty', icon: Icons.FlagPlIcon },
  CZ: { currency: 'Czech Koruna', icon: Icons.FlagCzIcon },
  HU: { currency: 'Hungarian Forint', icon: Icons.FlagHuIcon },
  RO: { currency: 'Romanian Leu', icon: Icons.FlagRoIcon },
  SE: { currency: 'Swedish Krona', icon: Icons.FlagSeIcon },
  NO: { currency: 'Norwegian Krone', icon: Icons.FlagNoIcon },
  DK: { currency: 'Danish Krone', icon: Icons.FlagDkIcon },
  IS: { currency: 'Icelandic Krona', icon: Icons.FlagIsIcon },
  IL: { currency: 'Israeli Shekel', icon: Icons.FlagIlIcon },
  SA: { currency: 'Saudi Riyal', icon: Icons.FlagSaIcon },
  AE: { currency: 'UAE Dirham', icon: Icons.FlagAeIcon },
  QA: { currency: 'Qatari Riyal', icon: Icons.FlagQaIcon },
  KW: { currency: 'Kuwaiti Dinar', icon: Icons.FlagKwIcon },
  BH: { currency: 'Bahraini Dinar', icon: Icons.FlagBhIcon },
  OM: { currency: 'Omani Rial', icon: Icons.FlagOmIcon },
  JO: { currency: 'Jordanian Dinar', icon: Icons.FlagJoIcon },
  EG: { currency: 'Egyptian Pound', icon: Icons.FlagEgIcon },
  NG: { currency: 'Nigerian Naira', icon: Icons.FlagNgIcon },
  KE: { currency: 'Kenyan Shilling', icon: Icons.FlagKeIcon },
  GH: { currency: 'Ghanaian Cedi', icon: Icons.FlagGhIcon },
  ET: { currency: 'Ethiopian Birr', icon: Icons.FlagEtIcon },
  TZ: { currency: 'Tanzanian Shilling', icon: Icons.FlagTz1Icon },
  UG: { currency: 'Ugandan Shilling', icon: Icons.FlagUgIcon },
  RW: { currency: 'Rwandan Franc', icon: Icons.FlagRwIcon },
  MA: { currency: 'Moroccan Dirham', icon: Icons.FlagMaIcon },
  TN: { currency: 'Tunisian Dinar', icon: Icons.FlagTnIcon },
  DZ: { currency: 'Algerian Dinar', icon: Icons.FlagDzIcon },
  LY: { currency: 'Libyan Dinar', icon: Icons.FlagLyIcon },
  PK: { currency: 'Pakistani Rupee', icon: Icons.FlagPkIcon },
  BD: { currency: 'Bangladeshi Taka', icon: Icons.FlagBdIcon },
  LK: { currency: 'Sri Lankan Rupee', icon: Icons.FlagLkIcon },
  NP: { currency: 'Nepalese Rupee', icon: Icons.FlagNpIcon },
  MM: { currency: 'Myanmar Kyat', icon: Icons.FlagMmIcon },
  KH: { currency: 'Cambodian Riel', icon: Icons.FlagKhIcon },
  LA: { currency: 'Lao Kip', icon: Icons.FlagLaIcon },
  KZ: { currency: 'Kazakhstani Tenge', icon: Icons.FlagKzIcon },
  UZ: { currency: 'Uzbekistani Som', icon: Icons.FlagUzIcon },
  GE: { currency: 'Georgian Lari', icon: Icons.FlagGeIcon },
  AM: { currency: 'Armenian Dram', icon: Icons.FlagAmIcon },
  AZ: { currency: 'Azerbaijani Manat', icon: Icons.FlagAzIcon },
  UA: { currency: 'Ukrainian Hryvnia', icon: Icons.FlagUaIcon },
  BY: { currency: 'Belarusian Ruble', icon: Icons.FlagByIcon },
  MD: { currency: 'Moldovan Leu', icon: Icons.FlagMdIcon },
  RS: { currency: 'Serbian Dinar', icon: Icons.FlagRsIcon },
  BA: { currency: 'Bosnia-Herzegovina Mark', icon: Icons.FlagBaIcon },
  MK: { currency: 'Macedonian Denar', icon: Icons.FlagMkIcon },
  AL: { currency: 'Albanian Lek', icon: Icons.FlagAlIcon },
  HR: { currency: 'Croatian Kuna', icon: Icons.FlagHrIcon },
  BG: { currency: 'Bulgarian Lev', icon: Icons.FlagBgIcon },
  TW: { currency: 'Taiwan Dollar', icon: Icons.FlagTwIcon },
  MO: { currency: 'Macanese Pataca', icon: Icons.FlagMoIcon },
  PY: { currency: 'Paraguayan Guaraní', icon: Icons.FlagPyIcon },
  UY: { currency: 'Uruguayan Peso', icon: Icons.FlagUyIcon },
  VE: { currency: 'Venezuelan Bolívar', icon: Icons.FlagVeIcon },
  GY: { currency: 'Guyanese Dollar', icon: Icons.FlagGyIcon },
  SR: { currency: 'Surinamese Dollar', icon: Icons.FlagSrIcon },
  TT: { currency: 'Trinidad & Tobago Dollar', icon: Icons.FlagTtIcon },
  JM: { currency: 'Jamaican Dollar', icon: Icons.FlagJmIcon },
  BB: { currency: 'Barbadian Dollar', icon: Icons.FlagBbIcon },
  BS: { currency: 'Bahamian Dollar', icon: Icons.FlagBsIcon },
  BZ: { currency: 'Belize Dollar', icon: Icons.FlagBzIcon },
  GT: { currency: 'Guatemalan Quetzal', icon: Icons.FlagGtIcon },
  HN: { currency: 'Honduran Lempira', icon: Icons.FlagHnIcon },
  NI: { currency: 'Nicaraguan Córdoba', icon: Icons.FlagNiIcon },
  CR: { currency: 'Costa Rican Colón', icon: Icons.FlagCrIcon },
  PA: { currency: 'Panamanian Balboa', icon: Icons.FlagPaIcon },
  CU: { currency: 'Cuban Peso', icon: Icons.FlagCuIcon },
  DO: { currency: 'Dominican Peso', icon: Icons.FlagDoIcon },
  FJ: { currency: 'Fijian Dollar', icon: Icons.FlagFjIcon },
  PG: { currency: 'Papua New Guinean Kina', icon: Icons.FlagPgIcon },
  SB: { currency: 'Solomon Islands Dollar', icon: Icons.FlagSbIcon },
  VU: { currency: 'Vanuatu Vatu', icon: Icons.FlagVuIcon },
  WS: { currency: 'Samoan Tala', icon: Icons.FlagWsIcon },
  TO: { currency: 'Tongan Paʻanga', icon: Icons.FlagToIcon },
}
